# To run: conda env create -f environment.yml
name: yobo_eval
channels:
    - conda-forge
dependencies:
    - python==3.7
    - pip
    - cudatoolkit=10.0
    - imagemagick
    - pip:
        - tensorflow-gpu==1.14
        - numpy
        - opencv-python
        - imageio
        - scikit-image==0.18.0
        - numba
        - protobuf==3.20.3
